/**
 * Auction Core API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductSchema } from './ProductSchema';
import { UserSchema } from './UserSchema';

export class AuctionSchema {
    'guid': string;
    'created': Date;
    'updated': Date;
    'isActive': boolean;
    'createdBy'?: UserSchema;
    'minBidPrice'?: number;
    'bidStarts'?: Date;
    'bidExpires'?: Date;
    'product': ProductSchema;
    'minRequiredCredit'?: number;
    'nextBid'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "guid",
            "baseName": "guid",
            "type": "string",
            "format": ""
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updated",
            "baseName": "updated",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "isActive",
            "baseName": "is_active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "createdBy",
            "baseName": "created_by",
            "type": "UserSchema",
            "format": ""
        },
        {
            "name": "minBidPrice",
            "baseName": "min_bid_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "bidStarts",
            "baseName": "bid_starts",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "bidExpires",
            "baseName": "bid_expires",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "product",
            "baseName": "product",
            "type": "ProductSchema",
            "format": ""
        },
        {
            "name": "minRequiredCredit",
            "baseName": "min_required_credit",
            "type": "number",
            "format": ""
        },
        {
            "name": "nextBid",
            "baseName": "next_bid",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AuctionSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

