/**
 * Auction Core API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateProductSchema {
    'minBidPrice'?: number;
    'bidStarts'?: Date;
    'bidExpires'?: Date;
    'category'?: string;
    'name': string;
    'description'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "minBidPrice",
            "baseName": "min_bid_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "bidStarts",
            "baseName": "bid_starts",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "bidExpires",
            "baseName": "bid_expires",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateProductSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

