/**
 * Auction Core API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ErrorCodes } from './ErrorCodes';
import { HttpFile } from '../http/http';

export class ErrorSchema {
    'error': string;
    'code': ErrorCodes;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "error",
            "baseName": "error",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "ErrorCodes",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ErrorSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

