/**
 * Auction Core API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ProductReviewCreateSchema {
    'productGuid': string;
    'rates'?: number;
    'comment'?: string;
    'isReported'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "productGuid",
            "baseName": "product_guid",
            "type": "string",
            "format": ""
        },
        {
            "name": "rates",
            "baseName": "rates",
            "type": "number",
            "format": ""
        },
        {
            "name": "comment",
            "baseName": "comment",
            "type": "string",
            "format": ""
        },
        {
            "name": "isReported",
            "baseName": "is_reported",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductReviewCreateSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

