/**
 * Auction Core API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CategorySchema } from './CategorySchema';
import { ProductImageSchema } from './ProductImageSchema';
import { UserSchema } from './UserSchema';
import { VerificationStatusTypes } from './VerificationStatusTypes';
import { HttpFile } from '../http/http';

export class ProductDetailsSchema {
    'guid': string;
    'created': Date;
    'updated': Date;
    'isActive': boolean;
    'isVerified': boolean;
    'verifiedBy'?: UserSchema;
    'verificationTimestamp'?: Date;
    'status': VerificationStatusTypes;
    'minBidPrice'?: number;
    'bidStarts'?: Date;
    'bidExpires'?: Date;
    'user': UserSchema;
    'category'?: CategorySchema;
    'name': string;
    'description'?: string;
    'isUpdatable'?: boolean;
    'images': Array<ProductImageSchema>;
    'verificationFilesCloudLink'?: string;
    'auctionGuid'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "guid",
            "baseName": "guid",
            "type": "string",
            "format": ""
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updated",
            "baseName": "updated",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "isActive",
            "baseName": "is_active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isVerified",
            "baseName": "is_verified",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "verifiedBy",
            "baseName": "verified_by",
            "type": "UserSchema",
            "format": ""
        },
        {
            "name": "verificationTimestamp",
            "baseName": "verification_timestamp",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "VerificationStatusTypes",
            "format": ""
        },
        {
            "name": "minBidPrice",
            "baseName": "min_bid_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "bidStarts",
            "baseName": "bid_starts",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "bidExpires",
            "baseName": "bid_expires",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "UserSchema",
            "format": ""
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "CategorySchema",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "isUpdatable",
            "baseName": "is_updatable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<ProductImageSchema>",
            "format": ""
        },
        {
            "name": "verificationFilesCloudLink",
            "baseName": "verification_files_cloud_link",
            "type": "string",
            "format": ""
        },
        {
            "name": "auctionGuid",
            "baseName": "auction_guid",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductDetailsSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

