/**
 * Auction Core API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserSchema } from './UserSchema';
import { UserTypeEnum } from './UserTypeEnum';
import { VerificationStatusTypes } from './VerificationStatusTypes';
import { HttpFile } from '../http/http';

export class ProfileSchema {
    'guid': string;
    'created': Date;
    'updated': Date;
    'isActive': boolean;
    'isVerified': boolean;
    'verifiedBy'?: UserSchema;
    'verificationTimestamp'?: Date;
    'status': VerificationStatusTypes;
    'canOperateProduct'?: boolean;
    'canAttendAuction'?: boolean;
    'canLogin'?: boolean;
    'user': UserSchema;
    'userType': UserTypeEnum;
    'verificationFilesCloudLink'?: string;
    'phoneNumber'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "guid",
            "baseName": "guid",
            "type": "string",
            "format": ""
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updated",
            "baseName": "updated",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "isActive",
            "baseName": "is_active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isVerified",
            "baseName": "is_verified",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "verifiedBy",
            "baseName": "verified_by",
            "type": "UserSchema",
            "format": ""
        },
        {
            "name": "verificationTimestamp",
            "baseName": "verification_timestamp",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "VerificationStatusTypes",
            "format": ""
        },
        {
            "name": "canOperateProduct",
            "baseName": "can_operate_product",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canAttendAuction",
            "baseName": "can_attend_auction",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canLogin",
            "baseName": "can_login",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "UserSchema",
            "format": ""
        },
        {
            "name": "userType",
            "baseName": "user_type",
            "type": "UserTypeEnum",
            "format": ""
        },
        {
            "name": "verificationFilesCloudLink",
            "baseName": "verification_files_cloud_link",
            "type": "string",
            "format": ""
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProfileSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

