/**
 * Auction Core API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProfileSchema } from './ProfileSchema';
import { HttpFile } from '../http/http';

export class UserTokenSchema {
    'accessToken': string;
    'profile': ProfileSchema;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "accessToken",
            "baseName": "accessToken",
            "type": "string",
            "format": ""
        },
        {
            "name": "profile",
            "baseName": "profile",
            "type": "ProfileSchema",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserTokenSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

